const express = require("express");
const Threat = require("../models/threat.js");
const Alert = require("../models/alert.js");
const Report = require("../models/report.js");

const router = express.Router();

// ✅ Generate report (dashboard analytics)
router.get("/generate", async (req, res) => {
  try {
    const totalThreats = await Threat.countDocuments();
    const activeThreats = await Threat.countDocuments({ status: "active" });
    const totalAlerts = await Alert.countDocuments();
    const criticalAlerts = await Alert.countDocuments({ severity: "Critical" });

    const report = await Report.create({
      summary: {
        totalThreats,
        activeThreats,
        totalAlerts,
        criticalAlerts,
      },
    });

    res.json({ message: "Report generated", report });
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
});

// ✅ Get latest reports
router.get("/", async (req, res) => {
  try {
    const reports = await Report.find().sort({ createdAt: -1 }).limit(10);
    res.json(reports);
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
});

module.exports = router;


// ---------------------------------------------------------------
// ✅ EXPORT REPORT TO PDF
// GET /api/reports/export/:id
// ---------------------------------------------------------------
router.get("/export/:id", async (req, res) => {
  try {
    const report = await Report.findById(req.params.id);

    if (!report) return res.status(404).json({ message: "Report not found" });

    const PDFDocument = require("pdfkit");
    const doc = new PDFDocument();

    res.setHeader("Content-Type", "application/pdf");
    res.setHeader(
      "Content-Disposition",
      `attachment; filename=threat-report-${report._id}.pdf`
    );

    doc.pipe(res);

    // ---------- Header --------------
    doc.fontSize(20).text("Threat Intelligence Report", { align: "center" });
    doc.moveDown();
    doc.fontSize(12).text(`Generated on: ${new Date().toLocaleString()}`);
    doc.moveDown();

    // ---------- Summary -------------
    doc.fontSize(16).text("Summary", { underline: true });
    doc.moveDown();

    const summary = report.summary;

    doc.fontSize(14).text(`Total Threats: ${summary.totalThreats}`);
    doc.text(`Active Threats: ${summary.activeThreats}`);
    doc.text(`Total Alerts: ${summary.totalAlerts}`);
    doc.text(`Critical Alerts: ${summary.criticalAlerts}`);
    doc.moveDown();

    // ---------- Footer --------------
    doc.moveDown().fontSize(10).text("Generated by ThreatView Dashboard");

    doc.end();
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
});